version: "3.4"

services:
  graphql-api:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    container_name: "open-fec-graphql"
    volumes:
      - "./:/usr/src/app"
    ports:
      - "5000:5000"
    stdin_open: true
    depends_on:
      - redis-cache
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
  redis-cache:
    image: redis:6.2.5
    container_name: "open-fec-graphql-cache"
    ports:
      - "6379:6379"
