version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.0

    steps:
      - checkout

      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev

      - run:
          command: |
            pipenv run test
